version: '3'
services:
  backend:
    build:
      context: ./src-api  # Ruta al directorio del backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000  # Puerto de la API

  frontend:
    build:
      context: ./src-frontend/camping-pong  # Ruta al directorio del frontend
      dockerfile: Dockerfile
    ports:
      - 80:80  # Puerto del frontend
    depends_on:
      - backend

